Fix compiler warning on shift overflow in QCA vendor definitions
Fix the following compiler error:
qca-vendor.h:5892:54: error: result of ‘1 << 31’ requires 33 bits to represent, but ‘int’ only has 32 bits [-Werror=shift-overflow=]
 5892 |  QCA_WLAN_VENDOR_CHANNEL_PROP_FLAG_HE40INTOL     = 1 << 31,

This "1" needs to be marked unsigned for this case of MSB=1.

Signed-off-by: Chaoli Zhou <quic_zchaoli@quicinc.com>

CRs-Fixed: 3309575
Git-repo: git://w1.fi/hostap.git
Git-commit: 1f39f85b7263c537b5564eccb5e82fed3f1fcd03
Change-Id: I1d095c6bf9a8a21b40631e430c3db9926e100d01